// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yagxplxxzttmgayenrst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZ3hwbHh4enR0bWdheWVucnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjU5NzUsImV4cCI6MjA2NDEwMTk3NX0.4FAxxAZrXACJpj5D7Mf522iJBhzUrVCnLrOT6fDH18o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);